export const SEASONAL_CAMPAIGNS = [
  {
    id: "volta-as-aulas-inicio",
    title: "Volta às Aulas",
    subtitle: "Material escolar, mochilas, uniformes, eletrônicos e tudo para recomeçar bem.",
    startsAt: "01-02",
    endsAt: "02-20",
    imageUrl:
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "volta as aulas",
      "volta às aulas",
      "escola",
      "material escolar",
      "mochila",
      "caderno",
      "lapis",
      "lápis",
      "caneta",
      "uniforme",
      "livro",
      "papelaria",
    ],
  },
  {
    id: "carnaval",
    title: "Carnaval no CompreTudo.shop",
    subtitle: "Fantasias, beleza, festas, bebidas, comidas e serviços para cair na folia.",
    startsAt: "01-28",
    endsAt: "02-17",
    imageUrl:
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "carnaval",
      "fantasia",
      "folia",
      "festa",
      "abadá",
      "abada",
      "maquiagem",
      "bebida",
      "som",
      "evento",
      "bloco",
      "confete",
    ],
  },
  {
    id: "dia-da-mulher",
    title: "Dia da Mulher",
    subtitle: "Presentes, beleza, moda, flores e experiências para valorizar mulheres especiais.",
    startsAt: "03-01",
    endsAt: "03-08",
    imageUrl:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "dia da mulher",
      "mulher",
      "presente",
      "flores",
      "flor",
      "beleza",
      "moda",
      "perfume",
      "salão",
      "salao",
      "spa",
      "estética",
      "estetica",
    ],
  },
  {
    id: "dia-do-consumidor",
    title: "Semana do Consumidor",
    subtitle: "Ofertas, descontos e oportunidades especiais nos comércios da cidade.",
    startsAt: "03-10",
    endsAt: "03-16",
    imageUrl:
      "https://images.unsplash.com/photo-1607082349566-187342175e2f?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "dia do consumidor",
      "consumidor",
      "desconto",
      "promo",
      "promocao",
      "promoção",
      "oferta",
      "liquidação",
      "liquidacao",
      "cupom",
      "imperdível",
    ],
  },
  {
    id: "semana-santa",
    title: "Semana Santa",
    subtitle: "Peixes, comidas especiais, viagens, encontros em família e serviços para o feriado.",
    startsAt: "03-29",
    endsAt: "04-05",
    imageUrl:
      "https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "semana santa",
      "sexta santa",
      "peixe",
      "pescado",
      "bacalhau",
      "almoço",
      "almoco",
      "familia",
      "família",
      "viagem",
      "feriado",
      "chocolate",
      "pascoa",
      "páscoa",
    ],
  },
  {
    id: "pascoa",
    title: "Páscoa no CompreTudo.shop",
    subtitle: "Chocolates, ovos, cestas, doces e presentes para celebrar a Páscoa.",
    startsAt: "03-06",
    endsAt: "04-05",
    imageUrl:
      "https://images.unsplash.com/photo-1521967906867-14ec9d64bee8?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "pascoa",
      "páscoa",
      "ovo de pascoa",
      "ovo de páscoa",
      "chocolate",
      "bombom",
      "cesta",
      "doce",
      "doces",
      "coelho",
      "presente",
      "kit",
    ],
  },
  {
    id: "dia-do-trabalhador",
    title: "Dia do Trabalhador",
    subtitle: "Serviços, ferramentas, uniformes, oportunidades e ofertas para quem movimenta a cidade.",
    startsAt: "04-20",
    endsAt: "05-01",
    imageUrl:
      "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "dia do trabalhador",
      "trabalhador",
      "serviço",
      "servico",
      "ferramenta",
      "uniforme",
      "bota",
      "epi",
      "construção",
      "construcao",
      "profissional",
      "oferta",
    ],
  },
  {
    id: "dia-das-maes",
    title: "Especial Dia das Mães",
    subtitle: "Presentes, kits, beleza, moda e experiências para surpreender.",
    startsAt: "05-01",
    endsAt: "05-11",
    imageUrl:
      "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "mae",
      "mãe",
      "dia das maes",
      "dia das mães",
      "presente",
      "kit",
      "flores",
      "flor",
      "perfume",
      "beleza",
      "spa",
      "salão",
      "salao",
    ],
  },
  {
    id: "dia-dos-namorados",
    title: "Dia dos Namorados",
    subtitle: "Presentes, jantares, flores, perfumes, moda e experiências para casais.",
    startsAt: "05-25",
    endsAt: "06-12",
    imageUrl:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "dia dos namorados",
      "namorados",
      "casal",
      "amor",
      "romantico",
      "romântico",
      "presente",
      "flores",
      "perfume",
      "jantar",
      "restaurante",
      "chocolate",
      "aliança",
      "alianca",
    ],
  },
  {
    id: "sao-joao",
    title: "São João no CompreTudo.shop",
    subtitle: "Produtos, comidas, roupas e serviços para curtir o período junino.",
    startsAt: "05-25",
    endsAt: "06-30",
    imageUrl:
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "sao joao",
      "são joão",
      "junino",
      "forro",
      "forró",
      "milho",
      "bota",
      "chapeu",
      "chapéu",
      "vestido",
      "comida típica",
      "quadrilha",
      "fogueira",
    ],
  },
  {
    id: "ferias-de-julho",
    title: "Férias de Julho",
    subtitle: "Passeios, lazer, comidas, hospedagens, brinquedos e experiências para aproveitar o mês.",
    startsAt: "07-01",
    endsAt: "07-31",
    imageUrl:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "ferias",
      "férias",
      "julho",
      "viagem",
      "passeio",
      "lazer",
      "criança",
      "crianca",
      "brinquedo",
      "restaurante",
      "hotel",
      "pousada",
      "parque",
    ],
  },
  {
    id: "volta-as-aulas-meio",
    title: "Volta às Aulas de Julho",
    subtitle: "Material escolar, mochilas, papelaria e itens para o segundo semestre.",
    startsAt: "07-15",
    endsAt: "08-10",
    imageUrl:
      "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "volta as aulas",
      "volta às aulas",
      "material escolar",
      "papelaria",
      "caderno",
      "mochila",
      "estojo",
      "lapis",
      "lápis",
      "caneta",
      "uniforme",
      "escola",
    ],
  },
  {
    id: "dia-dos-pais",
    title: "Dia dos Pais",
    subtitle: "Presentes, moda, perfumes, ferramentas, tecnologia e experiências para homenagear.",
    startsAt: "07-25",
    endsAt: "08-09",
    imageUrl:
      "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "pai",
      "pais",
      "dia dos pais",
      "presente",
      "perfume",
      "camisa",
      "moda masculina",
      "ferramenta",
      "churrasco",
      "relógio",
      "relogio",
      "carteira",
      "tecnologia",
    ],
  },
  {
    id: "semana-do-cliente",
    title: "Semana do Cliente",
    subtitle: "Ofertas especiais, vantagens e promoções para valorizar quem compra local.",
    startsAt: "09-10",
    endsAt: "09-20",
    imageUrl:
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "cliente",
      "semana do cliente",
      "desconto",
      "promo",
      "promocao",
      "promoção",
      "oferta",
      "cupom",
      "vantagem",
      "brinde",
      "liquidação",
      "liquidacao",
    ],
  },
  {
    id: "dia-das-criancas",
    title: "Dia das Crianças",
    subtitle: "Brinquedos, roupas, doces, passeios e presentes para alegrar os pequenos.",
    startsAt: "09-20",
    endsAt: "10-12",
    imageUrl:
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "dia das crianças",
      "dia das criancas",
      "criança",
      "crianca",
      "brinquedo",
      "boneca",
      "carrinho",
      "roupa infantil",
      "doce",
      "doces",
      "presente",
      "parque",
      "lazer",
    ],
  },
  {
    id: "outubro-rosa",
    title: "Outubro Rosa",
    subtitle: "Beleza, autocuidado, saúde, bem-estar e campanhas especiais durante outubro.",
    startsAt: "10-01",
    endsAt: "10-31",
    imageUrl:
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "outubro rosa",
      "rosa",
      "saude",
      "saúde",
      "mulher",
      "autocuidado",
      "beleza",
      "bem estar",
      "bem-estar",
      "exame",
      "clinica",
      "clínica",
      "estética",
      "estetica",
    ],
  },
  {
    id: "halloween",
    title: "Halloween",
    subtitle: "Fantasias, doces, decoração, festas e produtos criativos para o Dia das Bruxas.",
    startsAt: "10-10",
    endsAt: "10-31",
    imageUrl:
      "https://images.unsplash.com/photo-1509557965875-b88c97052f0e?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "halloween",
      "dia das bruxas",
      "bruxa",
      "fantasia",
      "doce",
      "doces",
      "festa",
      "decoração",
      "decoracao",
      "abobora",
      "abóbora",
      "maquiagem",
    ],
  },
  {
    id: "novembro-azul",
    title: "Novembro Azul",
    subtitle: "Saúde, autocuidado masculino, bem-estar e serviços especiais durante novembro.",
    startsAt: "11-01",
    endsAt: "11-30",
    imageUrl:
      "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "novembro azul",
      "azul",
      "saude",
      "saúde",
      "homem",
      "masculino",
      "autocuidado",
      "bem estar",
      "bem-estar",
      "clinica",
      "clínica",
      "barbearia",
      "exame",
    ],
  },
  {
    id: "black-friday",
    title: "Black Friday Local",
    subtitle: "Ofertas e achadinhos dos comércios da sua região.",
    startsAt: "11-10",
    endsAt: "11-30",
    imageUrl:
      "https://images.unsplash.com/photo-1607083206968-13611e3d76db?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "black friday",
      "desconto",
      "promo",
      "promocao",
      "promoção",
      "oferta",
      "imperdível",
      "liquidação",
      "liquidacao",
      "queima de estoque",
      "cupom",
    ],
  },
  {
    id: "natal",
    title: "Natal no CompreTudo.shop",
    subtitle: "Presentes, ceias, kits, decoração e serviços para o fim de ano.",
    startsAt: "12-01",
    endsAt: "12-25",
    imageUrl:
      "https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "natal",
      "presente",
      "ceia",
      "kit",
      "roupa",
      "decoracao",
      "decoração",
      "panetone",
      "arvore",
      "árvore",
      "brinquedo",
      "chocolate",
      "vinho",
    ],
  },
  {
    id: "reveillon",
    title: "Ano Novo / Réveillon",
    subtitle: "Looks, festas, ceias, viagens, beleza e tudo para começar o ano em grande estilo.",
    startsAt: "12-26",
    endsAt: "12-31",
    imageUrl:
      "https://images.unsplash.com/photo-1467810563316-b5476525c0f9?auto=format&fit=crop&w=1400&q=80",
    keywords: [
      "ano novo",
      "reveillon",
      "réveillon",
      "festa",
      "branco",
      "roupa branca",
      "look",
      "ceia",
      "viagem",
      "fogos",
      "bebida",
      "beleza",
      "salão",
      "salao",
    ],
  },
];

export const DEFAULT_SEASONAL_CAMPAIGN = {
  id: "achadinhos",
  title: "Achadinhos da cidade",
  subtitle: "Produtos, serviços e oportunidades que combinam com o momento.",
  imageUrl:
    "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1400&q=80",
  keywords: ["kit", "presente", "combo", "oferta", "novidade", "promo"],
};