export const DEFAULT_CATEGORIES = [
  "Pizzaria",
  "Restaurante",
  "Lanchonete",
  "Hamburgueria",
  "Açaí",
  "Padaria",
  "Mercado",
  "Farmácia",
  "Academia",
  "Salão de beleza",
  "Barbearia",
  "Clínica",
  "Dentista",
  "Petshop",
  "Oficina",
  "Auto elétrica",
  "Loja de roupas",
  "Material de construção",
  "Ótica",
  "Papelaria",
];