export const PRINT_CATEGORIES = [
  {
    id: "logo",
    label: "Logomarca",
    icon: "✨",
    description: "Criação, recuperação e melhoria de marcas.",
  },
  {
    id: "business_card",
    label: "Cartão de visita",
    icon: "💳",
    description: "Cartões simples, frente e verso e premium.",
  },
  {
    id: "flyer",
    label: "Panfletos",
    icon: "📄",
    description: "Panfletos para promoções e divulgação local.",
  },
  {
    id: "social",
    label: "Redes sociais",
    icon: "📱",
    description: "Posts, stories e criativos digitais.",
  },
  {
    id: "stickers",
    label: "Adesivos",
    icon: "🏷️",
    description: "Adesivos para embalagens e produtos.",
  },
  {
    id: "banners",
    label: "Banners",
    icon: "🖼️",
    description: "Banners para fachada, eventos e divulgação.",
  },
];

export const PRINT_PRODUCTS = [
  {
    id: "logo_creation",
    categoryId: "logo",
    name: "Criação de logomarca",
    subtitle: "Recupere, melhore ou crie uma logomarca profissional em PNG.",
    sizeLabel: "PNG transparente",
    widthMm: null,
    heightMm: null,
    bleedMm: 0,
    safeAreaMm: 0,
    dpi: 300,
    finalWidthPx: 1024,
    finalHeightPx: 1024,
    priceFrom: 29.9,
    icon: "✨",
    formats: ["PNG transparente"],
    type: "logo",
  },

  {
    id: "business_card_front",
    categoryId: "business_card",
    name: "Cartão frente",
    subtitle: "Cartão de visita simples com arte frontal.",
    sizeLabel: "9x5 cm",
    widthMm: 90,
    heightMm: 50,
    bleedMm: 3,
    safeAreaMm: 4,
    dpi: 300,
    finalWidthPx: 1134,
    finalHeightPx: 638,
    priceFrom: 49.9,
    icon: "💳",
    formats: ["PDF para impressão", "PNG de prévia"],
  },
  {
    id: "business_card_double",
    categoryId: "business_card",
    name: "Cartão frente e verso",
    subtitle: "Cartão completo com informações dos dois lados.",
    sizeLabel: "9x5 cm",
    widthMm: 90,
    heightMm: 50,
    bleedMm: 3,
    safeAreaMm: 4,
    dpi: 300,
    finalWidthPx: 1134,
    finalHeightPx: 638,
    priceFrom: 69.9,
    icon: "💳",
    formats: ["PDF para impressão", "PNG de prévia"],
  },
  {
    id: "business_card_premium",
    categoryId: "business_card",
    name: "Cartão premium",
    subtitle: "Modelo elegante para empresas e profissionais.",
    sizeLabel: "9x5 cm",
    widthMm: 90,
    heightMm: 50,
    bleedMm: 3,
    safeAreaMm: 4,
    dpi: 300,
    finalWidthPx: 1134,
    finalHeightPx: 638,
    priceFrom: 89.9,
    icon: "💎",
    formats: ["PDF para impressão", "PNG de prévia"],
  },

  {
    id: "flyer_10x15",
    categoryId: "flyer",
    name: "Panfleto 10x15",
    subtitle: "Perfeito para ofertas, campanhas e divulgação local.",
    sizeLabel: "10x15 cm",
    widthMm: 100,
    heightMm: 150,
    bleedMm: 3,
    safeAreaMm: 5,
    dpi: 300,
    finalWidthPx: 1252,
    finalHeightPx: 1843,
    priceFrom: 79.9,
    icon: "📄",
    formats: ["PDF para impressão", "PNG de prévia"],
  },
  {
    id: "flyer_15x21",
    categoryId: "flyer",
    name: "Panfleto 15x21",
    subtitle: "Mais espaço para divulgar produtos e serviços.",
    sizeLabel: "15x21 cm",
    widthMm: 150,
    heightMm: 210,
    bleedMm: 3,
    safeAreaMm: 5,
    dpi: 300,
    finalWidthPx: 1843,
    finalHeightPx: 2551,
    priceFrom: 99.9,
    icon: "📃",
    formats: ["PDF para impressão", "PNG de prévia"],
  },

  {
    id: "instagram_post",
    categoryId: "social",
    name: "Post Instagram",
    subtitle: "Criativo quadrado para divulgar produtos e serviços.",
    sizeLabel: "1080x1080 px",
    widthMm: null,
    heightMm: null,
    bleedMm: 0,
    safeAreaMm: 0,
    dpi: 72,
    finalWidthPx: 1080,
    finalHeightPx: 1080,
    priceFrom: 19.9,
    icon: "📱",
    formats: ["PNG digital"],
  },
  {
    id: "instagram_story",
    categoryId: "social",
    name: "Story Instagram",
    subtitle: "Arte vertical para stories, status e anúncios.",
    sizeLabel: "1080x1920 px",
    widthMm: null,
    heightMm: null,
    bleedMm: 0,
    safeAreaMm: 0,
    dpi: 72,
    finalWidthPx: 1080,
    finalHeightPx: 1920,
    priceFrom: 19.9,
    icon: "📲",
    formats: ["PNG digital"],
  },

  {
    id: "sticker_5x5",
    categoryId: "stickers",
    name: "Adesivo 5x5",
    subtitle: "Adesivo para embalagem, produto ou identidade visual.",
    sizeLabel: "5x5 cm",
    widthMm: 50,
    heightMm: 50,
    bleedMm: 2,
    safeAreaMm: 3,
    dpi: 300,
    finalWidthPx: 638,
    finalHeightPx: 638,
    priceFrom: 39.9,
    icon: "🏷️",
    formats: ["PDF para impressão", "PNG de prévia"],
  },

  {
    id: "banner_120x90",
    categoryId: "banners",
    name: "Banner 120x90",
    subtitle: "Banner para fachada, eventos e divulgação física.",
    sizeLabel: "120x90 cm",
    widthMm: 1200,
    heightMm: 900,
    bleedMm: 10,
    safeAreaMm: 30,
    dpi: 150,
    finalWidthPx: 7200,
    finalHeightPx: 5400,
    priceFrom: 99.9,
    icon: "🖼️",
    formats: ["PDF para impressão"],
  },
];

export function formatMoneyBR(value) {
  return Number(value || 0).toLocaleString("pt-BR", {
    style: "currency",
    currency: "BRL",
  });
}